"""
CFFI-generated stub file.
This file was automatically generated from C declarations.
"""

from dataclasses import dataclass
from typing import Any, Callable, Final, Literal, TypeAlias, TypedDict, Union
from cffi import FFI
from _typeshed import Self

CData = FFI.CData

# Unknown macro values
PN_RECEIVED: Final[int]
PN_ACCEPTED: Final[int]
PN_REJECTED: Final[int]
PN_RELEASED: Final[int]
PN_MODIFIED: Final[int]
PN_DECLARED: Final[int]
PN_TRANSACTIONAL_STATE: Final[int]
PN_DEFAULT_PRIORITY: Final[int]
PN_OK: Final[int]
PN_EOS: Final[int]
PN_OVERFLOW: Final[int]
PN_TIMEOUT: Final[int]
PN_INTR: Final[int]
PN_LOCAL_UNINIT: Final[int]
PN_LOCAL_ACTIVE: Final[int]
PN_LOCAL_CLOSED: Final[int]
PN_REMOTE_UNINIT: Final[int]
PN_REMOTE_ACTIVE: Final[int]
PN_REMOTE_CLOSED: Final[int]
PN_TRACE_OFF: Final[int]
PN_TRACE_RAW: Final[int]
PN_TRACE_FRM: Final[int]
PN_TRACE_DRV: Final[int]
PN_VERSION_MAJOR: Final[int]
PN_VERSION_MINOR: Final[int]
PN_VERSION_POINT: Final[int]


# Type aliases
pn_char_t = int
pn_decimal32_t = int
pn_decimal64_t = int
pn_millis_t = int
pn_seconds_t = int
pn_sequence_t = int
pn_state_t = int
pn_timestamp_t = int
pn_trace_t = int


# Enums
PN_DIST_MODE_UNSPECIFIED: TypeAlias = Literal[0]  # pn_distribution_mode_t
PN_DIST_MODE_COPY: TypeAlias = Literal[1]  # pn_distribution_mode_t
PN_DIST_MODE_MOVE: TypeAlias = Literal[2]  # pn_distribution_mode_t
pn_distribution_mode_t = Union[PN_DIST_MODE_UNSPECIFIED, PN_DIST_MODE_COPY, PN_DIST_MODE_MOVE]

PN_NONDURABLE: TypeAlias = Literal[0]  # pn_durability_t
PN_CONFIGURATION: TypeAlias = Literal[1]  # pn_durability_t
PN_DELIVERIES: TypeAlias = Literal[2]  # pn_durability_t
pn_durability_t = Union[PN_NONDURABLE, PN_CONFIGURATION, PN_DELIVERIES]

PN_EVENT_NONE: TypeAlias = Literal[0]  # pn_event_type_t
PN_REACTOR_INIT: TypeAlias = Literal[1]  # pn_event_type_t
PN_REACTOR_QUIESCED: TypeAlias = Literal[2]  # pn_event_type_t
PN_REACTOR_FINAL: TypeAlias = Literal[3]  # pn_event_type_t
PN_TIMER_TASK: TypeAlias = Literal[4]  # pn_event_type_t
PN_CONNECTION_INIT: TypeAlias = Literal[5]  # pn_event_type_t
PN_CONNECTION_BOUND: TypeAlias = Literal[6]  # pn_event_type_t
PN_CONNECTION_UNBOUND: TypeAlias = Literal[7]  # pn_event_type_t
PN_CONNECTION_LOCAL_OPEN: TypeAlias = Literal[8]  # pn_event_type_t
PN_CONNECTION_REMOTE_OPEN: TypeAlias = Literal[9]  # pn_event_type_t
PN_CONNECTION_LOCAL_CLOSE: TypeAlias = Literal[10]  # pn_event_type_t
PN_CONNECTION_REMOTE_CLOSE: TypeAlias = Literal[11]  # pn_event_type_t
PN_CONNECTION_FINAL: TypeAlias = Literal[12]  # pn_event_type_t
PN_SESSION_INIT: TypeAlias = Literal[13]  # pn_event_type_t
PN_SESSION_LOCAL_OPEN: TypeAlias = Literal[14]  # pn_event_type_t
PN_SESSION_REMOTE_OPEN: TypeAlias = Literal[15]  # pn_event_type_t
PN_SESSION_LOCAL_CLOSE: TypeAlias = Literal[16]  # pn_event_type_t
PN_SESSION_REMOTE_CLOSE: TypeAlias = Literal[17]  # pn_event_type_t
PN_SESSION_FINAL: TypeAlias = Literal[18]  # pn_event_type_t
PN_LINK_INIT: TypeAlias = Literal[19]  # pn_event_type_t
PN_LINK_LOCAL_OPEN: TypeAlias = Literal[20]  # pn_event_type_t
PN_LINK_REMOTE_OPEN: TypeAlias = Literal[21]  # pn_event_type_t
PN_LINK_LOCAL_CLOSE: TypeAlias = Literal[22]  # pn_event_type_t
PN_LINK_REMOTE_CLOSE: TypeAlias = Literal[23]  # pn_event_type_t
PN_LINK_LOCAL_DETACH: TypeAlias = Literal[24]  # pn_event_type_t
PN_LINK_REMOTE_DETACH: TypeAlias = Literal[25]  # pn_event_type_t
PN_LINK_FLOW: TypeAlias = Literal[26]  # pn_event_type_t
PN_LINK_FINAL: TypeAlias = Literal[27]  # pn_event_type_t
PN_DELIVERY: TypeAlias = Literal[28]  # pn_event_type_t
PN_TRANSPORT: TypeAlias = Literal[29]  # pn_event_type_t
PN_TRANSPORT_AUTHENTICATED: TypeAlias = Literal[30]  # pn_event_type_t
PN_TRANSPORT_ERROR: TypeAlias = Literal[31]  # pn_event_type_t
PN_TRANSPORT_HEAD_CLOSED: TypeAlias = Literal[32]  # pn_event_type_t
PN_TRANSPORT_TAIL_CLOSED: TypeAlias = Literal[33]  # pn_event_type_t
PN_TRANSPORT_CLOSED: TypeAlias = Literal[34]  # pn_event_type_t
PN_SELECTABLE_INIT: TypeAlias = Literal[35]  # pn_event_type_t
PN_SELECTABLE_UPDATED: TypeAlias = Literal[36]  # pn_event_type_t
PN_SELECTABLE_READABLE: TypeAlias = Literal[37]  # pn_event_type_t
PN_SELECTABLE_WRITABLE: TypeAlias = Literal[38]  # pn_event_type_t
PN_SELECTABLE_ERROR: TypeAlias = Literal[39]  # pn_event_type_t
PN_SELECTABLE_EXPIRED: TypeAlias = Literal[40]  # pn_event_type_t
PN_SELECTABLE_FINAL: TypeAlias = Literal[41]  # pn_event_type_t
PN_CONNECTION_WAKE: TypeAlias = Literal[42]  # pn_event_type_t
PN_LISTENER_ACCEPT: TypeAlias = Literal[43]  # pn_event_type_t
PN_LISTENER_CLOSE: TypeAlias = Literal[44]  # pn_event_type_t
PN_PROACTOR_INTERRUPT: TypeAlias = Literal[45]  # pn_event_type_t
PN_PROACTOR_TIMEOUT: TypeAlias = Literal[46]  # pn_event_type_t
PN_PROACTOR_INACTIVE: TypeAlias = Literal[47]  # pn_event_type_t
PN_LISTENER_OPEN: TypeAlias = Literal[48]  # pn_event_type_t
PN_RAW_CONNECTION_CONNECTED: TypeAlias = Literal[49]  # pn_event_type_t
PN_RAW_CONNECTION_CLOSED_READ: TypeAlias = Literal[50]  # pn_event_type_t
PN_RAW_CONNECTION_CLOSED_WRITE: TypeAlias = Literal[51]  # pn_event_type_t
PN_RAW_CONNECTION_DISCONNECTED: TypeAlias = Literal[52]  # pn_event_type_t
PN_RAW_CONNECTION_NEED_READ_BUFFERS: TypeAlias = Literal[53]  # pn_event_type_t
PN_RAW_CONNECTION_NEED_WRITE_BUFFERS: TypeAlias = Literal[54]  # pn_event_type_t
PN_RAW_CONNECTION_READ: TypeAlias = Literal[55]  # pn_event_type_t
PN_RAW_CONNECTION_WRITTEN: TypeAlias = Literal[56]  # pn_event_type_t
PN_RAW_CONNECTION_WAKE: TypeAlias = Literal[57]  # pn_event_type_t
PN_RAW_CONNECTION_DRAIN_BUFFERS: TypeAlias = Literal[58]  # pn_event_type_t
pn_event_type_t = Union[PN_EVENT_NONE, PN_REACTOR_INIT, PN_REACTOR_QUIESCED, PN_REACTOR_FINAL, PN_TIMER_TASK, PN_CONNECTION_INIT, PN_CONNECTION_BOUND, PN_CONNECTION_UNBOUND, PN_CONNECTION_LOCAL_OPEN, PN_CONNECTION_REMOTE_OPEN, PN_CONNECTION_LOCAL_CLOSE, PN_CONNECTION_REMOTE_CLOSE, PN_CONNECTION_FINAL, PN_SESSION_INIT, PN_SESSION_LOCAL_OPEN, PN_SESSION_REMOTE_OPEN, PN_SESSION_LOCAL_CLOSE, PN_SESSION_REMOTE_CLOSE, PN_SESSION_FINAL, PN_LINK_INIT, PN_LINK_LOCAL_OPEN, PN_LINK_REMOTE_OPEN, PN_LINK_LOCAL_CLOSE, PN_LINK_REMOTE_CLOSE, PN_LINK_LOCAL_DETACH, PN_LINK_REMOTE_DETACH, PN_LINK_FLOW, PN_LINK_FINAL, PN_DELIVERY, PN_TRANSPORT, PN_TRANSPORT_AUTHENTICATED, PN_TRANSPORT_ERROR, PN_TRANSPORT_HEAD_CLOSED, PN_TRANSPORT_TAIL_CLOSED, PN_TRANSPORT_CLOSED, PN_SELECTABLE_INIT, PN_SELECTABLE_UPDATED, PN_SELECTABLE_READABLE, PN_SELECTABLE_WRITABLE, PN_SELECTABLE_ERROR, PN_SELECTABLE_EXPIRED, PN_SELECTABLE_FINAL, PN_CONNECTION_WAKE, PN_LISTENER_ACCEPT, PN_LISTENER_CLOSE, PN_PROACTOR_INTERRUPT, PN_PROACTOR_TIMEOUT, PN_PROACTOR_INACTIVE, PN_LISTENER_OPEN, PN_RAW_CONNECTION_CONNECTED, PN_RAW_CONNECTION_CLOSED_READ, PN_RAW_CONNECTION_CLOSED_WRITE, PN_RAW_CONNECTION_DISCONNECTED, PN_RAW_CONNECTION_NEED_READ_BUFFERS, PN_RAW_CONNECTION_NEED_WRITE_BUFFERS, PN_RAW_CONNECTION_READ, PN_RAW_CONNECTION_WRITTEN, PN_RAW_CONNECTION_WAKE, PN_RAW_CONNECTION_DRAIN_BUFFERS]

PN_EXPIRE_WITH_LINK: TypeAlias = Literal[0]  # pn_expiry_policy_t
PN_EXPIRE_WITH_SESSION: TypeAlias = Literal[1]  # pn_expiry_policy_t
PN_EXPIRE_WITH_CONNECTION: TypeAlias = Literal[2]  # pn_expiry_policy_t
PN_EXPIRE_NEVER: TypeAlias = Literal[3]  # pn_expiry_policy_t
pn_expiry_policy_t = Union[PN_EXPIRE_WITH_LINK, PN_EXPIRE_WITH_SESSION, PN_EXPIRE_WITH_CONNECTION, PN_EXPIRE_NEVER]

PN_RCV_FIRST: TypeAlias = Literal[0]  # pn_rcv_settle_mode_t
PN_RCV_SECOND: TypeAlias = Literal[1]  # pn_rcv_settle_mode_t
pn_rcv_settle_mode_t = Union[PN_RCV_FIRST, PN_RCV_SECOND]

PN_SASL_NONE: TypeAlias = Literal[-1]  # pn_sasl_outcome_t
PN_SASL_OK: TypeAlias = Literal[0]  # pn_sasl_outcome_t
PN_SASL_AUTH: TypeAlias = Literal[1]  # pn_sasl_outcome_t
PN_SASL_SYS: TypeAlias = Literal[2]  # pn_sasl_outcome_t
PN_SASL_PERM: TypeAlias = Literal[3]  # pn_sasl_outcome_t
PN_SASL_TEMP: TypeAlias = Literal[4]  # pn_sasl_outcome_t
pn_sasl_outcome_t = Union[PN_SASL_NONE, PN_SASL_OK, PN_SASL_AUTH, PN_SASL_SYS, PN_SASL_PERM, PN_SASL_TEMP]

PN_SND_UNSETTLED: TypeAlias = Literal[0]  # pn_snd_settle_mode_t
PN_SND_SETTLED: TypeAlias = Literal[1]  # pn_snd_settle_mode_t
PN_SND_MIXED: TypeAlias = Literal[2]  # pn_snd_settle_mode_t
pn_snd_settle_mode_t = Union[PN_SND_UNSETTLED, PN_SND_SETTLED, PN_SND_MIXED]

PN_SSL_CERT_SUBJECT_COUNTRY_NAME: TypeAlias = Literal[0]  # pn_ssl_cert_subject_subfield
PN_SSL_CERT_SUBJECT_STATE_OR_PROVINCE: TypeAlias = Literal[1]  # pn_ssl_cert_subject_subfield
PN_SSL_CERT_SUBJECT_CITY_OR_LOCALITY: TypeAlias = Literal[2]  # pn_ssl_cert_subject_subfield
PN_SSL_CERT_SUBJECT_ORGANIZATION_NAME: TypeAlias = Literal[3]  # pn_ssl_cert_subject_subfield
PN_SSL_CERT_SUBJECT_ORGANIZATION_UNIT: TypeAlias = Literal[4]  # pn_ssl_cert_subject_subfield
PN_SSL_CERT_SUBJECT_COMMON_NAME: TypeAlias = Literal[5]  # pn_ssl_cert_subject_subfield
pn_ssl_cert_subject_subfield = Union[PN_SSL_CERT_SUBJECT_COUNTRY_NAME, PN_SSL_CERT_SUBJECT_STATE_OR_PROVINCE, PN_SSL_CERT_SUBJECT_CITY_OR_LOCALITY, PN_SSL_CERT_SUBJECT_ORGANIZATION_NAME, PN_SSL_CERT_SUBJECT_ORGANIZATION_UNIT, PN_SSL_CERT_SUBJECT_COMMON_NAME]

PN_SSL_SHA1: TypeAlias = Literal[0]  # pn_ssl_hash_alg
PN_SSL_SHA256: TypeAlias = Literal[1]  # pn_ssl_hash_alg
PN_SSL_SHA512: TypeAlias = Literal[2]  # pn_ssl_hash_alg
PN_SSL_MD5: TypeAlias = Literal[3]  # pn_ssl_hash_alg
pn_ssl_hash_alg = Union[PN_SSL_SHA1, PN_SSL_SHA256, PN_SSL_SHA512, PN_SSL_MD5]

PN_SSL_MODE_CLIENT: TypeAlias = Literal[1]  # pn_ssl_mode_t
PN_SSL_MODE_SERVER: TypeAlias = Literal[2]  # pn_ssl_mode_t
pn_ssl_mode_t = Union[PN_SSL_MODE_CLIENT, PN_SSL_MODE_SERVER]

PN_SSL_RESUME_UNKNOWN: TypeAlias = Literal[0]  # pn_ssl_resume_status_t
PN_SSL_RESUME_NEW: TypeAlias = Literal[1]  # pn_ssl_resume_status_t
PN_SSL_RESUME_REUSED: TypeAlias = Literal[2]  # pn_ssl_resume_status_t
pn_ssl_resume_status_t = Union[PN_SSL_RESUME_UNKNOWN, PN_SSL_RESUME_NEW, PN_SSL_RESUME_REUSED]

PN_SSL_VERIFY_NULL: TypeAlias = Literal[0]  # pn_ssl_verify_mode_t
PN_SSL_VERIFY_PEER: TypeAlias = Literal[1]  # pn_ssl_verify_mode_t
PN_SSL_ANONYMOUS_PEER: TypeAlias = Literal[2]  # pn_ssl_verify_mode_t
PN_SSL_VERIFY_PEER_NAME: TypeAlias = Literal[3]  # pn_ssl_verify_mode_t
pn_ssl_verify_mode_t = Union[PN_SSL_VERIFY_NULL, PN_SSL_VERIFY_PEER, PN_SSL_ANONYMOUS_PEER, PN_SSL_VERIFY_PEER_NAME]

PN_UNSPECIFIED: TypeAlias = Literal[0]  # pn_terminus_type_t
PN_SOURCE: TypeAlias = Literal[1]  # pn_terminus_type_t
PN_TARGET: TypeAlias = Literal[2]  # pn_terminus_type_t
PN_COORDINATOR: TypeAlias = Literal[3]  # pn_terminus_type_t
pn_terminus_type_t = Union[PN_UNSPECIFIED, PN_SOURCE, PN_TARGET, PN_COORDINATOR]

PN_NULL: TypeAlias = Literal[1]  # pn_type_t
PN_BOOL: TypeAlias = Literal[2]  # pn_type_t
PN_UBYTE: TypeAlias = Literal[3]  # pn_type_t
PN_BYTE: TypeAlias = Literal[4]  # pn_type_t
PN_USHORT: TypeAlias = Literal[5]  # pn_type_t
PN_SHORT: TypeAlias = Literal[6]  # pn_type_t
PN_UINT: TypeAlias = Literal[7]  # pn_type_t
PN_INT: TypeAlias = Literal[8]  # pn_type_t
PN_CHAR: TypeAlias = Literal[9]  # pn_type_t
PN_ULONG: TypeAlias = Literal[10]  # pn_type_t
PN_LONG: TypeAlias = Literal[11]  # pn_type_t
PN_TIMESTAMP: TypeAlias = Literal[12]  # pn_type_t
PN_FLOAT: TypeAlias = Literal[13]  # pn_type_t
PN_DOUBLE: TypeAlias = Literal[14]  # pn_type_t
PN_DECIMAL32: TypeAlias = Literal[15]  # pn_type_t
PN_DECIMAL64: TypeAlias = Literal[16]  # pn_type_t
PN_DECIMAL128: TypeAlias = Literal[17]  # pn_type_t
PN_UUID: TypeAlias = Literal[18]  # pn_type_t
PN_BINARY: TypeAlias = Literal[19]  # pn_type_t
PN_STRING: TypeAlias = Literal[20]  # pn_type_t
PN_SYMBOL: TypeAlias = Literal[21]  # pn_type_t
PN_DESCRIBED: TypeAlias = Literal[22]  # pn_type_t
PN_ARRAY: TypeAlias = Literal[23]  # pn_type_t
PN_LIST: TypeAlias = Literal[24]  # pn_type_t
PN_MAP: TypeAlias = Literal[25]  # pn_type_t
PN_INVALID: TypeAlias = Literal[-1]  # pn_type_t
pn_type_t = Union[PN_NULL, PN_BOOL, PN_UBYTE, PN_BYTE, PN_USHORT, PN_SHORT, PN_UINT, PN_INT, PN_CHAR, PN_ULONG, PN_LONG, PN_TIMESTAMP, PN_FLOAT, PN_DOUBLE, PN_DECIMAL32, PN_DECIMAL64, PN_DECIMAL128, PN_UUID, PN_BINARY, PN_STRING, PN_SYMBOL, PN_DESCRIBED, PN_ARRAY, PN_LIST, PN_MAP, PN_INVALID]


# Structures
@dataclass
class pn_bytes_t:
    size: int
    start: CData


class pn_collector_t: ...
class pn_condition_t: ...
class pn_connection_t: ...
class pn_data_t: ...


class pn_decimal128_t:
    bytes: CData
    def __getitem__(self: Self, index: int) -> Self: ...


class pn_delivery_t: ...
class pn_disposition_t: ...
class pn_error_t: ...
class pn_event_t: ...
class pn_link_t: ...
class pn_message_t: ...
class pn_record_t: ...
class pn_sasl_t: ...
class pn_session_t: ...
class pn_ssl_domain_t: ...
class pn_ssl_t: ...
class pn_terminus_t: ...
class pn_transport_t: ...


class pn_uuid_t:
    bytes: CData
    def __getitem__(self: Self, index: int) -> Self: ...


class pn_atom_t:
    type: pn_type_t
    u: Any


class pn_custom_disposition_t: ...
class pn_received_disposition_t: ...
class pn_rejected_disposition_t: ...
class pn_modified_disposition_t: ...
class pn_declared_disposition_t: ...
class pn_transactional_disposition_t: ...


# More type aliases
pn_delivery_tag_t = pn_bytes_t
pn_msgid_t = pn_atom_t
pn_tracer_t = Callable


# Functions
def pn_collector() -> pn_collector_t: ...
def pn_collector_free(collector: pn_collector_t) -> None: ...
def pn_collector_more(collector: pn_collector_t) -> bool: ...
def pn_collector_peek(collector: pn_collector_t) -> pn_event_t: ...
def pn_collector_pop(collector: pn_collector_t) -> bool: ...
def pn_collector_release(collector: pn_collector_t) -> None: ...
def pn_condition_clear(condition: pn_condition_t) -> None: ...
def pn_condition_get_description(condition: pn_condition_t) -> bytes: ...
def pn_condition_get_name(condition: pn_condition_t) -> bytes: ...
def pn_condition_info(condition: pn_condition_t) -> pn_data_t: ...
def pn_condition_is_set(condition: pn_condition_t) -> bool: ...
def pn_condition_set_description(condition: pn_condition_t, description: bytes) -> int: ...
def pn_condition_set_name(condition: pn_condition_t, name: bytes) -> int: ...
def pn_connection() -> pn_connection_t: ...
def pn_connection_attachments(connection: pn_connection_t) -> pn_record_t: ...
def pn_connection_close(connection: pn_connection_t) -> None: ...
def pn_connection_collect(connection: pn_connection_t, collector: pn_collector_t) -> None: ...
def pn_connection_condition(connection: pn_connection_t) -> pn_condition_t: ...
def pn_connection_desired_capabilities(connection: pn_connection_t) -> pn_data_t: ...
def pn_connection_error(connection: pn_connection_t) -> pn_error_t: ...
def pn_connection_get_authorization(connection: pn_connection_t) -> bytes: ...
def pn_connection_get_container(connection: pn_connection_t) -> bytes: ...
def pn_connection_get_hostname(connection: pn_connection_t) -> bytes: ...
def pn_connection_get_user(connection: pn_connection_t) -> bytes: ...
def pn_connection_offered_capabilities(connection: pn_connection_t) -> pn_data_t: ...
def pn_connection_open(connection: pn_connection_t) -> None: ...
def pn_connection_properties(connection: pn_connection_t) -> pn_data_t: ...
def pn_connection_release(connection: pn_connection_t) -> None: ...
def pn_connection_remote_condition(connection: pn_connection_t) -> pn_condition_t: ...
def pn_connection_remote_container(connection: pn_connection_t) -> bytes: ...
def pn_connection_remote_desired_capabilities(connection: pn_connection_t) -> pn_data_t: ...
def pn_connection_remote_hostname(connection: pn_connection_t) -> bytes: ...
def pn_connection_remote_offered_capabilities(connection: pn_connection_t) -> pn_data_t: ...
def pn_connection_remote_properties(connection: pn_connection_t) -> pn_data_t: ...
def pn_connection_set_authorization(connection: pn_connection_t, authzid: bytes) -> None: ...
def pn_connection_set_container(connection: pn_connection_t, container: bytes) -> None: ...
def pn_connection_set_hostname(connection: pn_connection_t, hostname: bytes) -> None: ...
def pn_connection_set_password(connection: pn_connection_t, password: bytes) -> None: ...
def pn_connection_set_user(connection: pn_connection_t, user: bytes) -> None: ...
def pn_connection_state(connection: pn_connection_t) -> int: ...
def pn_connection_transport(connection: pn_connection_t) -> pn_transport_t: ...
def pn_data(capacity: int) -> pn_data_t: ...
def pn_data_clear(data: pn_data_t) -> None: ...
def pn_data_copy(data: pn_data_t, src: pn_data_t) -> int: ...
def pn_data_decode(data: pn_data_t, bytes: CData, size: int) -> int: ...
def pn_data_dump(data: pn_data_t) -> None: ...
def pn_data_encode(data: pn_data_t, bytes: CData, size: int) -> int: ...
def pn_data_encoded_size(data: pn_data_t) -> int: ...
def pn_data_enter(data: pn_data_t) -> bool: ...
def pn_data_error(data: pn_data_t) -> pn_error_t: ...
def pn_data_exit(data: pn_data_t) -> bool: ...
def pn_data_free(data: pn_data_t) -> None: ...
def pn_data_get_array(data: pn_data_t) -> int: ...
def pn_data_get_array_type(data: pn_data_t) -> pn_type_t: ...
def pn_data_get_binary(data: pn_data_t) -> pn_bytes_t: ...
def pn_data_get_bool(data: pn_data_t) -> bool: ...
def pn_data_get_byte(data: pn_data_t) -> int: ...
def pn_data_get_char(data: pn_data_t) -> int: ...
def pn_data_get_decimal128(data: pn_data_t) -> pn_decimal128_t: ...
def pn_data_get_decimal32(data: pn_data_t) -> int: ...
def pn_data_get_decimal64(data: pn_data_t) -> int: ...
def pn_data_get_double(data: pn_data_t) -> float: ...
def pn_data_get_float(data: pn_data_t) -> float: ...
def pn_data_get_int(data: pn_data_t) -> int: ...
def pn_data_get_list(data: pn_data_t) -> int: ...
def pn_data_get_long(data: pn_data_t) -> int: ...
def pn_data_get_map(data: pn_data_t) -> int: ...
def pn_data_get_short(data: pn_data_t) -> int: ...
def pn_data_get_string(data: pn_data_t) -> pn_bytes_t: ...
def pn_data_get_symbol(data: pn_data_t) -> pn_bytes_t: ...
def pn_data_get_timestamp(data: pn_data_t) -> int: ...
def pn_data_get_ubyte(data: pn_data_t) -> int: ...
def pn_data_get_uint(data: pn_data_t) -> int: ...
def pn_data_get_ulong(data: pn_data_t) -> int: ...
def pn_data_get_ushort(data: pn_data_t) -> int: ...
def pn_data_get_uuid(data: pn_data_t) -> pn_uuid_t: ...
def pn_data_is_array_described(data: pn_data_t) -> bool: ...
def pn_data_is_described(data: pn_data_t) -> bool: ...
def pn_data_is_null(data: pn_data_t) -> bool: ...
def pn_data_lookup(data: pn_data_t, name: bytes) -> bool: ...
def pn_data_narrow(data: pn_data_t) -> None: ...
def pn_data_next(data: pn_data_t) -> bool: ...
def pn_data_prev(data: pn_data_t) -> bool: ...
def pn_data_put_array(data: pn_data_t, described: bool, type: pn_type_t) -> int: ...
def pn_data_put_binary(data: pn_data_t, bytes: pn_bytes_t) -> int: ...
def pn_data_put_bool(data: pn_data_t, b: bool) -> int: ...
def pn_data_put_byte(data: pn_data_t, b: int) -> int: ...
def pn_data_put_char(data: pn_data_t, c: int) -> int: ...
def pn_data_put_decimal128(data: pn_data_t, d: pn_decimal128_t) -> int: ...
def pn_data_put_decimal32(data: pn_data_t, d: int) -> int: ...
def pn_data_put_decimal64(data: pn_data_t, d: int) -> int: ...
def pn_data_put_described(data: pn_data_t) -> int: ...
def pn_data_put_double(data: pn_data_t, d: float) -> int: ...
def pn_data_put_float(data: pn_data_t, f: float) -> int: ...
def pn_data_put_int(data: pn_data_t, i: int) -> int: ...
def pn_data_put_list(data: pn_data_t) -> int: ...
def pn_data_put_long(data: pn_data_t, l: int) -> int: ...
def pn_data_put_map(data: pn_data_t) -> int: ...
def pn_data_put_null(data: pn_data_t) -> int: ...
def pn_data_put_short(data: pn_data_t, s: int) -> int: ...
def pn_data_put_string(data: pn_data_t, string: pn_bytes_t) -> int: ...
def pn_data_put_symbol(data: pn_data_t, symbol: pn_bytes_t) -> int: ...
def pn_data_put_timestamp(data: pn_data_t, t: int) -> int: ...
def pn_data_put_ubyte(data: pn_data_t, ub: int) -> int: ...
def pn_data_put_uint(data: pn_data_t, ui: int) -> int: ...
def pn_data_put_ulong(data: pn_data_t, ul: int) -> int: ...
def pn_data_put_ushort(data: pn_data_t, us: int) -> int: ...
def pn_data_put_uuid(data: pn_data_t, u: pn_uuid_t) -> int: ...
def pn_data_rewind(data: pn_data_t) -> None: ...
def pn_data_type(data: pn_data_t) -> pn_type_t: ...
def pn_data_widen(data: pn_data_t) -> None: ...
def pn_decref(object: Any) -> int: ...
def pn_tostring(object: Any) -> CData: ...
def pn_delivery(link: pn_link_t, tag: pn_bytes_t) -> pn_delivery_t: ...
def pn_delivery_abort(delivery: pn_delivery_t) -> None: ...
def pn_delivery_aborted(delivery: pn_delivery_t) -> bool: ...
def pn_delivery_attachments(delivery: pn_delivery_t) -> pn_record_t: ...
def pn_delivery_link(delivery: pn_delivery_t) -> pn_link_t: ...
def pn_delivery_local(delivery: pn_delivery_t) -> pn_disposition_t: ...
def pn_delivery_local_state(delivery: pn_delivery_t) -> int: ...
def pn_delivery_partial(delivery: pn_delivery_t) -> bool: ...
def pn_delivery_pending(delivery: pn_delivery_t) -> int: ...
def pn_delivery_readable(delivery: pn_delivery_t) -> bool: ...
def pn_delivery_remote(delivery: pn_delivery_t) -> pn_disposition_t: ...
def pn_delivery_remote_state(delivery: pn_delivery_t) -> int: ...
def pn_delivery_settle(delivery: pn_delivery_t) -> None: ...
def pn_delivery_settled(delivery: pn_delivery_t) -> bool: ...
def pn_delivery_tag(delivery: pn_delivery_t) -> pn_bytes_t: ...
def pn_delivery_update(delivery: pn_delivery_t, state: int) -> None: ...
def pn_delivery_updated(delivery: pn_delivery_t) -> bool: ...
def pn_delivery_writable(delivery: pn_delivery_t) -> bool: ...
def pn_disposition_annotations(disposition: pn_disposition_t) -> pn_data_t: ...
def pn_disposition_condition(disposition: pn_disposition_t) -> pn_condition_t: ...
def pn_disposition_data(disposition: pn_disposition_t) -> pn_data_t: ...
def pn_disposition_get_section_number(disposition: pn_disposition_t) -> int: ...
def pn_disposition_get_section_offset(disposition: pn_disposition_t) -> int: ...
def pn_disposition_is_failed(disposition: pn_disposition_t) -> bool: ...
def pn_disposition_is_undeliverable(disposition: pn_disposition_t) -> bool: ...
def pn_disposition_set_failed(disposition: pn_disposition_t, failed: bool) -> None: ...
def pn_disposition_set_section_number(disposition: pn_disposition_t, section_number: int) -> None: ...
def pn_disposition_set_section_offset(disposition: pn_disposition_t, section_offset: int) -> None: ...
def pn_disposition_set_undeliverable(disposition: pn_disposition_t, undeliverable: bool) -> None: ...
def pn_disposition_type(disposition: pn_disposition_t) -> int: ...
def pn_custom_disposition(disposition: pn_disposition_t) -> pn_custom_disposition_t: ...
def pn_received_disposition(disposition: pn_disposition_t) -> pn_received_disposition_t: ...
def pn_rejected_disposition(disposition: pn_disposition_t) -> pn_rejected_disposition_t: ...
def pn_modified_disposition(disposition: pn_disposition_t) -> pn_modified_disposition_t: ...
def pn_declared_disposition(disposition: pn_disposition_t) -> pn_declared_disposition_t: ...
def pn_transactional_disposition(disposition: pn_disposition_t) -> pn_transactional_disposition_t: ...
def pn_custom_disposition_set_type(disposition: pn_custom_disposition_t, type: int) -> None: ...
def pn_custom_disposition_get_type(disposition: pn_custom_disposition_t) -> int: ...
def pn_custom_disposition_data(disposition: pn_custom_disposition_t) -> pn_data_t: ...
def pn_rejected_disposition_condition(disposition: pn_rejected_disposition_t) -> pn_condition_t: ...
def pn_received_disposition_get_section_number(disposition: pn_received_disposition_t) -> int: ...
def pn_received_disposition_set_section_number(disposition: pn_received_disposition_t, section_number: int) -> None: ...
def pn_received_disposition_get_section_offset(disposition: pn_received_disposition_t) -> int: ...
def pn_received_disposition_set_section_offset(disposition: pn_received_disposition_t, section_offset: int) -> None: ...
def pn_modified_disposition_is_failed(disposition: pn_modified_disposition_t) -> bool: ...
def pn_modified_disposition_set_failed(disposition: pn_modified_disposition_t, failed: bool) -> None: ...
def pn_modified_disposition_is_undeliverable(disposition: pn_modified_disposition_t) -> bool: ...
def pn_modified_disposition_set_undeliverable(disposition: pn_modified_disposition_t, undeliverable: bool) -> None: ...
def pn_modified_disposition_annotations(disposition: pn_modified_disposition_t) -> pn_data_t: ...
def pn_declared_disposition_get_id(disposition: pn_declared_disposition_t) -> pn_bytes_t: ...
def pn_declared_disposition_set_id(disposition: pn_declared_disposition_t, id: pn_bytes_t) -> None: ...
def pn_transactional_disposition_get_id(disposition: pn_transactional_disposition_t) -> pn_bytes_t: ...
def pn_transactional_disposition_set_id(disposition: pn_transactional_disposition_t, id: pn_bytes_t) -> None: ...
def pn_transactional_disposition_get_outcome_type(disposition: pn_transactional_disposition_t) -> int: ...
def pn_transactional_disposition_set_outcome_type(disposition: pn_transactional_disposition_t, outcome: int) -> None: ...
def pn_error_code(error: pn_error_t) -> int: ...
def pn_error_text(error: pn_error_t) -> bytes: ...
def pn_event_connection(event: pn_event_t) -> pn_connection_t: ...
def pn_event_context(event: pn_event_t) -> Any: ...
def pn_event_delivery(event: pn_event_t) -> pn_delivery_t: ...
def pn_event_link(event: pn_event_t) -> pn_link_t: ...
def pn_event_session(event: pn_event_t) -> pn_session_t: ...
def pn_event_transport(event: pn_event_t) -> pn_transport_t: ...
def pn_event_type(event: pn_event_t) -> pn_event_type_t: ...
def pn_event_type_name(type: pn_event_type_t) -> bytes: ...
def pn_incref(object: Any) -> Any: ...
def pn_link_advance(link: pn_link_t) -> bool: ...
def pn_link_attachments(link: pn_link_t) -> pn_record_t: ...
def pn_link_available(link: pn_link_t) -> int: ...
def pn_link_close(link: pn_link_t) -> None: ...
def pn_link_condition(link: pn_link_t) -> pn_condition_t: ...
def pn_link_credit(link: pn_link_t) -> int: ...
def pn_link_current(link: pn_link_t) -> pn_delivery_t: ...
def pn_link_detach(link: pn_link_t) -> None: ...
def pn_link_drain(receiver: pn_link_t, credit: int) -> None: ...
def pn_link_drained(link: pn_link_t) -> int: ...
def pn_link_draining(receiver: pn_link_t) -> bool: ...
def pn_link_error(link: pn_link_t) -> pn_error_t: ...
def pn_link_flow(receiver: pn_link_t, credit: int) -> None: ...
def pn_link_free(link: pn_link_t) -> None: ...
def pn_link_get_drain(link: pn_link_t) -> bool: ...
def pn_link_head(connection: pn_connection_t, state: int) -> pn_link_t: ...
def pn_link_is_receiver(link: pn_link_t) -> bool: ...
def pn_link_is_sender(link: pn_link_t) -> bool: ...
def pn_link_max_message_size(link: pn_link_t) -> int: ...
def pn_link_name(link: pn_link_t) -> bytes: ...
def pn_link_next(link: pn_link_t, state: int) -> pn_link_t: ...
def pn_link_offered(sender: pn_link_t, credit: int) -> None: ...
def pn_link_open(link: pn_link_t) -> None: ...
def pn_link_properties(link: pn_link_t) -> pn_data_t: ...
def pn_link_queued(link: pn_link_t) -> int: ...
def pn_link_rcv_settle_mode(link: pn_link_t) -> pn_rcv_settle_mode_t: ...
def pn_link_recv(receiver: pn_link_t, bytes: CData, n: int) -> int: ...
def pn_link_remote_condition(link: pn_link_t) -> pn_condition_t: ...
def pn_link_remote_max_message_size(link: pn_link_t) -> int: ...
def pn_link_remote_properties(link: pn_link_t) -> pn_data_t: ...
def pn_link_remote_rcv_settle_mode(link: pn_link_t) -> pn_rcv_settle_mode_t: ...
def pn_link_remote_snd_settle_mode(link: pn_link_t) -> pn_snd_settle_mode_t: ...
def pn_link_remote_source(link: pn_link_t) -> pn_terminus_t: ...
def pn_link_remote_target(link: pn_link_t) -> pn_terminus_t: ...
def pn_link_send(sender: pn_link_t, bytes: CData, n: int) -> int: ...
def pn_link_session(link: pn_link_t) -> pn_session_t: ...
def pn_link_set_drain(receiver: pn_link_t, drain: bool) -> None: ...
def pn_link_set_max_message_size(link: pn_link_t, size: int) -> None: ...
def pn_link_set_rcv_settle_mode(link: pn_link_t, mode: pn_rcv_settle_mode_t) -> None: ...
def pn_link_set_snd_settle_mode(link: pn_link_t, mode: pn_snd_settle_mode_t) -> None: ...
def pn_link_snd_settle_mode(link: pn_link_t) -> pn_snd_settle_mode_t: ...
def pn_link_source(link: pn_link_t) -> pn_terminus_t: ...
def pn_link_state(link: pn_link_t) -> int: ...
def pn_link_target(link: pn_link_t) -> pn_terminus_t: ...
def pn_link_unsettled(link: pn_link_t) -> int: ...
def pn_message() -> pn_message_t: ...
def pn_message_annotations(msg: pn_message_t) -> pn_data_t: ...
def pn_message_body(msg: pn_message_t) -> pn_data_t: ...
def pn_message_clear(msg: pn_message_t) -> None: ...
def pn_message_decode(msg: pn_message_t, bytes: CData, size: int) -> int: ...
def pn_message_error(msg: pn_message_t) -> pn_error_t: ...
def pn_message_free(msg: pn_message_t) -> None: ...
def pn_message_get_address(msg: pn_message_t) -> bytes: ...
def pn_message_get_content_encoding(msg: pn_message_t) -> bytes: ...
def pn_message_get_content_type(msg: pn_message_t) -> bytes: ...
def pn_message_get_correlation_id(msg: pn_message_t) -> pn_atom_t: ...
def pn_message_get_creation_time(msg: pn_message_t) -> int: ...
def pn_message_get_delivery_count(msg: pn_message_t) -> int: ...
def pn_message_get_expiry_time(msg: pn_message_t) -> int: ...
def pn_message_get_group_id(msg: pn_message_t) -> bytes: ...
def pn_message_get_group_sequence(msg: pn_message_t) -> int: ...
def pn_message_get_id(msg: pn_message_t) -> pn_atom_t: ...
def pn_message_get_priority(msg: pn_message_t) -> int: ...
def pn_message_get_reply_to(msg: pn_message_t) -> bytes: ...
def pn_message_get_reply_to_group_id(msg: pn_message_t) -> bytes: ...
def pn_message_get_subject(msg: pn_message_t) -> bytes: ...
def pn_message_get_ttl(msg: pn_message_t) -> int: ...
def pn_message_get_user_id(msg: pn_message_t) -> pn_bytes_t: ...
def pn_message_instructions(msg: pn_message_t) -> pn_data_t: ...
def pn_message_is_durable(msg: pn_message_t) -> bool: ...
def pn_message_is_first_acquirer(msg: pn_message_t) -> bool: ...
def pn_message_is_inferred(msg: pn_message_t) -> bool: ...
def pn_message_properties(msg: pn_message_t) -> pn_data_t: ...
def pn_message_set_address(msg: pn_message_t, address: bytes) -> int: ...
def pn_message_set_content_encoding(msg: pn_message_t, encoding: bytes) -> int: ...
def pn_message_set_content_type(msg: pn_message_t, type: bytes) -> int: ...
def pn_message_set_correlation_id(msg: pn_message_t, id: pn_atom_t) -> int: ...
def pn_message_set_creation_time(msg: pn_message_t, time: int) -> int: ...
def pn_message_set_delivery_count(msg: pn_message_t, count: int) -> int: ...
def pn_message_set_durable(msg: pn_message_t, durable: bool) -> int: ...
def pn_message_set_expiry_time(msg: pn_message_t, time: int) -> int: ...
def pn_message_set_first_acquirer(msg: pn_message_t, first: bool) -> int: ...
def pn_message_set_group_id(msg: pn_message_t, group_id: bytes) -> int: ...
def pn_message_set_group_sequence(msg: pn_message_t, n: int) -> int: ...
def pn_message_set_id(msg: pn_message_t, id: pn_atom_t) -> int: ...
def pn_message_set_inferred(msg: pn_message_t, inferred: bool) -> int: ...
def pn_message_set_priority(msg: pn_message_t, priority: int) -> int: ...
def pn_message_set_reply_to(msg: pn_message_t, reply_to: bytes) -> int: ...
def pn_message_set_reply_to_group_id(msg: pn_message_t, reply_to_group_id: bytes) -> int: ...
def pn_message_set_subject(msg: pn_message_t, subject: bytes) -> int: ...
def pn_message_set_ttl(msg: pn_message_t, ttl: int) -> int: ...
def pn_message_set_user_id(msg: pn_message_t, user_id: pn_bytes_t) -> int: ...
def pn_unsettled_head(link: pn_link_t) -> pn_delivery_t: ...
def pn_unsettled_next(delivery: pn_delivery_t) -> pn_delivery_t: ...
def pn_receiver(session: pn_session_t, name: bytes) -> pn_link_t: ...
def pn_sasl(transport: pn_transport_t) -> pn_sasl_t: ...
def pn_sasl_allowed_mechs(sasl: pn_sasl_t, mechs: bytes) -> None: ...
def pn_sasl_config_name(sasl: pn_sasl_t, name: bytes) -> None: ...
def pn_sasl_config_path(sasl: pn_sasl_t, path: bytes) -> None: ...
def pn_sasl_done(sasl: pn_sasl_t, outcome: pn_sasl_outcome_t) -> None: ...
def pn_sasl_extended() -> bool: ...
def pn_sasl_get_allow_insecure_mechs(sasl: pn_sasl_t) -> bool: ...
def pn_sasl_get_authorization(sasl: pn_sasl_t) -> bytes: ...
def pn_sasl_get_mech(sasl: pn_sasl_t) -> bytes: ...
def pn_sasl_get_user(sasl: pn_sasl_t) -> bytes: ...
def pn_sasl_outcome(sasl: pn_sasl_t) -> pn_sasl_outcome_t: ...
def pn_sasl_set_allow_insecure_mechs(sasl: pn_sasl_t, insecure: bool) -> None: ...
def pn_sender(session: pn_session_t, name: bytes) -> pn_link_t: ...
def pn_session(connection: pn_connection_t) -> pn_session_t: ...
def pn_session_attachments(session: pn_session_t) -> pn_record_t: ...
def pn_session_close(session: pn_session_t) -> None: ...
def pn_session_condition(session: pn_session_t) -> pn_condition_t: ...
def pn_session_connection(session: pn_session_t) -> pn_connection_t: ...
def pn_session_free(session: pn_session_t) -> None: ...
def pn_session_get_incoming_capacity(session: pn_session_t) -> int: ...
def pn_session_get_outgoing_window(session: pn_session_t) -> int: ...
def pn_session_head(connection: pn_connection_t, state: int) -> pn_session_t: ...
def pn_session_incoming_bytes(session: pn_session_t) -> int: ...
def pn_session_next(session: pn_session_t, state: int) -> pn_session_t: ...
def pn_session_open(session: pn_session_t) -> None: ...
def pn_session_outgoing_bytes(session: pn_session_t) -> int: ...
def pn_session_remote_condition(session: pn_session_t) -> pn_condition_t: ...
def pn_session_set_incoming_capacity(session: pn_session_t, capacity: int) -> None: ...
def pn_session_set_outgoing_window(session: pn_session_t, window: int) -> None: ...
def pn_session_state(session: pn_session_t) -> int: ...
def pn_ssl(transport: pn_transport_t) -> pn_ssl_t: ...
def pn_ssl_domain(mode: pn_ssl_mode_t) -> pn_ssl_domain_t: ...
def pn_ssl_domain_allow_unsecured_client(domain: pn_ssl_domain_t) -> int: ...
def pn_ssl_domain_free(domain: pn_ssl_domain_t) -> None: ...
def pn_ssl_domain_set_ciphers(domain: pn_ssl_domain_t, ciphers: bytes) -> int: ...
def pn_ssl_domain_set_credentials(domain: pn_ssl_domain_t, credential_1: bytes, credential_2: bytes, password: bytes) -> int: ...
def pn_ssl_domain_set_peer_authentication(domain: pn_ssl_domain_t, mode: pn_ssl_verify_mode_t, trusted_CAs: bytes) -> int: ...
def pn_ssl_domain_set_protocols(domain: pn_ssl_domain_t, protocols: bytes) -> int: ...
def pn_ssl_domain_set_trusted_ca_db(domain: pn_ssl_domain_t, certificate_db: bytes) -> int: ...
def pn_ssl_get_cert_fingerprint(ssl0: pn_ssl_t, fingerprint: bytes, fingerprint_length: int, hash_alg: pn_ssl_hash_alg) -> int: ...
def pn_ssl_get_cipher_name(ssl: pn_ssl_t, buffer: bytes, size: int) -> bool: ...
def pn_ssl_get_protocol_name(ssl: pn_ssl_t, buffer: bytes, size: int) -> bool: ...
def pn_ssl_get_remote_subject(ssl: pn_ssl_t) -> bytes: ...
def pn_ssl_get_remote_subject_subfield(ssl0: pn_ssl_t, field: pn_ssl_cert_subject_subfield) -> bytes: ...
def pn_ssl_init(ssl: pn_ssl_t, domain: pn_ssl_domain_t, session_id: bytes) -> int: ...
def pn_ssl_present() -> bool: ...
def pn_ssl_resume_status(ssl: pn_ssl_t) -> pn_ssl_resume_status_t: ...
def pn_ssl_set_peer_hostname(ssl: pn_ssl_t, hostname: bytes) -> int: ...
def pn_terminus_capabilities(terminus: pn_terminus_t) -> pn_data_t: ...
def pn_terminus_copy(terminus: pn_terminus_t, src: pn_terminus_t) -> int: ...
def pn_terminus_filter(terminus: pn_terminus_t) -> pn_data_t: ...
def pn_terminus_get_address(terminus: pn_terminus_t) -> bytes: ...
def pn_terminus_get_distribution_mode(terminus: pn_terminus_t) -> pn_distribution_mode_t: ...
def pn_terminus_get_durability(terminus: pn_terminus_t) -> pn_durability_t: ...
def pn_terminus_get_expiry_policy(terminus: pn_terminus_t) -> pn_expiry_policy_t: ...
def pn_terminus_get_timeout(terminus: pn_terminus_t) -> int: ...
def pn_terminus_get_type(terminus: pn_terminus_t) -> pn_terminus_type_t: ...
def pn_terminus_is_dynamic(terminus: pn_terminus_t) -> bool: ...
def pn_terminus_outcomes(terminus: pn_terminus_t) -> pn_data_t: ...
def pn_terminus_properties(terminus: pn_terminus_t) -> pn_data_t: ...
def pn_terminus_set_address(terminus: pn_terminus_t, address: bytes) -> int: ...
def pn_terminus_set_distribution_mode(terminus: pn_terminus_t, mode: pn_distribution_mode_t) -> int: ...
def pn_terminus_set_durability(terminus: pn_terminus_t, durability: pn_durability_t) -> int: ...
def pn_terminus_set_dynamic(terminus: pn_terminus_t, dynamic: bool) -> int: ...
def pn_terminus_set_expiry_policy(terminus: pn_terminus_t, policy: pn_expiry_policy_t) -> int: ...
def pn_terminus_set_timeout(terminus: pn_terminus_t, timeout: int) -> int: ...
def pn_terminus_set_type(terminus: pn_terminus_t, type: pn_terminus_type_t) -> int: ...
def pn_transport() -> pn_transport_t: ...
def pn_transport_attachments(transport: pn_transport_t) -> pn_record_t: ...
def pn_transport_bind(transport: pn_transport_t, connection: pn_connection_t) -> int: ...
def pn_transport_capacity(transport: pn_transport_t) -> int: ...
def pn_transport_close_head(transport: pn_transport_t) -> int: ...
def pn_transport_close_tail(transport: pn_transport_t) -> int: ...
def pn_transport_closed(transport: pn_transport_t) -> bool: ...
def pn_transport_condition(transport: pn_transport_t) -> pn_condition_t: ...
def pn_transport_connection(transport: pn_transport_t) -> pn_connection_t: ...
def pn_transport_error(transport: pn_transport_t) -> pn_error_t: ...
def pn_transport_get_channel_max(transport: pn_transport_t) -> int: ...
def pn_transport_get_frames_input(transport: pn_transport_t) -> int: ...
def pn_transport_get_frames_output(transport: pn_transport_t) -> int: ...
def pn_transport_get_idle_timeout(transport: pn_transport_t) -> int: ...
def pn_transport_get_max_frame(transport: pn_transport_t) -> int: ...
def pn_transport_get_remote_idle_timeout(transport: pn_transport_t) -> int: ...
def pn_transport_get_remote_max_frame(transport: pn_transport_t) -> int: ...
def pn_transport_get_user(transport: pn_transport_t) -> bytes: ...
def pn_transport_is_authenticated(transport: pn_transport_t) -> bool: ...
def pn_transport_is_encrypted(transport: pn_transport_t) -> bool: ...
def pn_transport_log(transport: pn_transport_t, message: bytes) -> None: ...
def pn_transport_peek(transport: pn_transport_t, dst: CData, size: int) -> int: ...
def pn_transport_pending(transport: pn_transport_t) -> int: ...
def pn_transport_pop(transport: pn_transport_t, size: int) -> None: ...
def pn_transport_push(transport: pn_transport_t, src: CData, size: int) -> int: ...
def pn_transport_remote_channel_max(transport: pn_transport_t) -> int: ...
def pn_transport_require_auth(transport: pn_transport_t, required: bool) -> None: ...
def pn_transport_require_encryption(transport: pn_transport_t, required: bool) -> None: ...
def pn_transport_set_channel_max(transport: pn_transport_t, channel_max: int) -> int: ...
def pn_transport_set_idle_timeout(transport: pn_transport_t, timeout: int) -> None: ...
def pn_transport_set_max_frame(transport: pn_transport_t, size: int) -> None: ...
def pn_transport_set_server(transport: pn_transport_t) -> None: ...
def pn_transport_set_tracer(transport: pn_transport_t, tracer: Callable) -> None: ...
def pn_transport_tick(transport: pn_transport_t, now: int) -> int: ...
def pn_transport_trace(transport: pn_transport_t, trace: int) -> None: ...
def pn_transport_unbind(transport: pn_transport_t) -> int: ...


def init() -> None: ...
def pn_cast_pn_connection(x: Any) -> pn_connection_t: ...
def pn_cast_pn_session(x: Any) -> pn_session_t: ...
def pn_cast_pn_link(x: Any) -> pn_link_t: ...
def pn_cast_pn_delivery(x: Any) -> pn_delivery_t: ...
def pn_cast_pn_transport(x: Any) -> pn_transport_t: ...
def pn_pyref_incref(object: Any) -> None: ...
def pn_pyref_decref(object: Any) -> None: ...
def pn_pytracer(transport: pn_transport_t, message: bytes) -> None: ...
def pn_collector_put_py(collector: pn_collector_t, context: Any, type: pn_event_type_t) -> pn_event_t: ...
def pn_data_format_py(data: pn_data_t, bytes: CData, size: int) -> int: ...
def pn_event_class_name_py(event: pn_event_t) -> CData: ...
def pn_message_encode_py(msg: pn_message_t, bytes: CData, size: int) -> int: ...
def pn_record_def_py(record: pn_record_t) -> None: ...
def pn_record_get_py(record: pn_record_t) -> Any: ...
def pn_record_set_py(record: pn_record_t, value: Any) -> None: ...
def pn_ssl_get_peer_hostname_py(ssl: pn_ssl_t, hostname: bytes, size: int) -> int: ...
def free(object: Any) -> None: ...
