from typing import (
    Any,
    Optional,
    Union
)
from uuid import UUID


def isinteger(value: Any) -> bool: ...
def isstring(value: Any) -> bool: ...


def millis2secs(millis: int) -> float: ...
def secs2millis(secs: float) -> int: ...


def unicode2utf8(string: Optional[str]) -> Optional[str]: ...
def utf82unicode(string: Optional[Union[str, bytes]]) -> Optional[str]: ...


class Constant:
    def __init__(self, name: str) -> None: ...
