from typing import (
    Any,
    Callable,
    List,
    Optional,
    Type,
    Union,
    Tuple
)

from proton._reactor import Reactor

_DEFAULT: bool

class Selectable:
    def __init__(self, reactor: Reactor) -> None: ...
    def fileno(self, fd:Union[bool, None, int] =_DEFAULT) -> Optional[int]: ...
    def _get_deadline(self) -> Optional[float]: ...
    def _set_deadline(self, deadline: float) -> None: ...
    deadline = property(_get_deadline, _set_deadline)
    def readable(self) -> None: ...
    def writable(self) -> None: ...
    def expired(self) -> None: ...
    @property
    def is_terminal(self) -> bool: ...
    def terminate(self) -> None: ...
