from typing import (
    Any
)

class pn_object_t: ...

class pn_transport_t: ...
class pn_ssl_t: ...
class pn_sasl_t: ...

class pn_connection_t: ...
class pn_session_t: ...
class pn_link_t: ...
class pn_sender_t: ...
class pn_receiver_t: ...
class pn_delivery_t: ...
class pn_terminus_t: ...
class pn_message_t: ...


class pn_data_t: ...

class pn_condition_t: ...

# PROTON_ERROR_H

PN_OK : int
PN_EOS : int
PN_ERR : int
PN_OVERFLOW : int
PN_UNDERFLOW : int
PN_STATE_ERR : int
PN_ARG_ERR : int
PN_TIMEOUT : int
PN_INTR : int
PN_INPROGRESS : int
PN_OUT_OF_MEMORY : int
PN_ABORTED : int

# Below here added in response to pycharm complaints

# __init__.py
PN_VERSION_MAJOR: int
PN_VERSION_MINOR: int
PN_VERSION_POINT: int

# _condition.py
def pn_condition_clear(): ...
def pn_condition_set_name(): ...
def pn_condition_set_description(): ...
def pn_condition_info(): ...
def pn_condition_is_set(): ...
def pn_condition_get_name(): ...
def pn_condition_get_description(): ...

# reactor.py
PN_MILLIS_MAX: int
PN_PYREF: int
PN_ACCEPTED: int
PN_EVENT_NONE: int
PN_CONNECTION_FINAL: int

# _event.py
class pn_collector_t: ...

def pn_collector() -> pn_collector_t: ...
def pn_py2void(object) -> Any: ...

# _endpoints.py
def pn_reactor_get_connection_address(): ...
def pn_reactor_set_connection_host(): ...
